# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Mod Properties
mod_id=capecommand
mod_name=Cape Command
mod_description=Adds a /cape command to use whichever cape you like

version=0.3.1-26.2

# Publishing
maven_group=xyz.eclipseisoffline
archives_base_name=capecommand

release_type=STABLE
modrinth_project_id=Ck0I4Uep
github_repository=eclipseisoffline/capecommand
git_branch=main
